### ISSUE TITLE
能打包成apk吗，我不会安卓开发，谢谢你

### ISSUE THREAD

**Issue by 707806032** [HappyMax0/NotificationSync#1]

**Comment by 707806032** [comment]
能回答下我吗，谢谢作者😊😊😊😊😊

**Comment by HappyMax0** [comment]
明天休息帮你弄

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by HappyMax0** [comment]
[https://res.cdn.office.net/assets/mail/file-icon/png/exe_16x16.png]app-release.apk<https://1drv.ms/u/c/1948D6F00C0300A4/EbvMfgdKEVRMvCsNrUKv3MEBa2fEA02fVoFPX9qUUGW4OQ>

________________________________
发件人: 707806032 ***@***.***>
发送时间: 2024年12月13日 5:11
收件人: HappyMax0/NotificationSync ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [HappyMax0/NotificationSync] 能打包成apk吗，我不会安卓开发，谢谢你 (Issue #1)


能回答下我吗，谢谢作者😊😊😊😊😊

**Comment by 707806032** [comment]
谢谢你呀，你是个好人😊😊😊😊😊
